language: go

go:
 - 1.3.1
 - tip
matrix:
  fast_finish: true
env:
  global:
    - PATH=$HOME/gopath/bin:$PATH
    - secure: "Eb4PuqNQ6nXupfvulFtO7XMw8f46VFHCJTW7YrGa2uBcI1ondsGn7lGkxVl3HgIpK65AZQJGlHbAm1FB+R5FN7KPO6iNMWtTBSepJYjc2iwl+a1eFB6wjW0ZKZfG1JcFXLSqp45NMuFBhQaFN0wZDQ4xmYcOAxR8X8Np3qgCwiA="

install:
 - go get code.google.com/p/go.tools/cmd/vet code.google.com/p/go.tools/cmd/cover github.com/mattn/goveralls github.com/modocache/gover
 - go get -t -v ./...
 - go install -a -race std

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
 - go list -f '{{if len .TestGoFiles}}go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}{{end}}' ./... | xargs -i sh -c {}
 - gover
 - goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
